version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    expose:
      - 27017

  app:
    build: .
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - mongo
    environment:
      - MONGODB_CONN_STRING=mongodb://root:secret@mongo:27017/?maxPoolSize=20&w=majority
